server.port=8083
spring.application.name=vehicle-service

spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=BoxCarsJwtSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm!!

management.endpoints.web.exposure.include=health,info
